__author__ = 'ryan'
ESI_Dict = {Fishing lures and lines : High,
Plastic rope / Small Net Pieces : High,
Rope or Net Pieces (non-nylon) : High,
Crab/Lobster/Fish trap parts : High,
Fishing nets : High,
Crab Trap in Need of Removal : High,
Rope : High,
Cigarettes : Low,
Plastic Bottle or Container Caps : Low,
Straws : Low,
Cigarette lighters/tobacco packaging : Low,
Cigarette or tobacco packaging : Low,
Metal Bottle Caps : Low,
Plastic Food Wrappers : Low,
Food wrappers (paper) : Low,
Clothing and Shoes : Low,
Aluminum or tin cans : Low,
Plastic Bottle : Low,
Foam or Plastic Cups : Low,
Plastic Utensils : Low,
Paper and Cardboard : Low,
Plastic Bags : Low,
Styrofoam packaging : Low,
Personal care products : Low,
Other Plastic Jugs or Containers : Low,
Gloves (non-rubber) : Low,
Flip-flops : Low,
Fireworks : Low,
Chemicals and chemical containers : Low,
Paper Cups : Low,
Towels or rags : Low,
Rubber Gloves : Low,
Non-food related plastic packaging : Low,
Marine Debris : Low,
Unknown number of Microplastic Pieces : Low,
Less than 100 Microplastic Pieces : Low,
200,000 or more Microplastic Pieces : Low,
Beverage Bottles (Plastic) : Low,
Beverage Bottles (Glass) : Low,
Cups & Plastes (Paper) : Low,
Food Wrappers : Low,
Grocery Bags (Plastic) : Low,
Other Plastic Bags : Low,
Bottle Caps (plastic) : Low,
Cigarrette Butts : Low,
Beverage Cans : Low,
Straws/Stirrers : Low,
Plastic Pieces : Low,
Lumber/Building Materials : Medium,
Plastic or Foam Fragments : Medium,
Toys (plastic) : Medium,
Balloons and/or string : Medium,
Tires : Medium,
Fabric pieces : Medium,
Six-pack rings : Medium,
Buoys and floats : Medium,
Batteries (acidic and alkaline) : Medium,
Pallets : Medium,
Take Out/Away Containers (Plastic) : Medium,
}